@startuml
left to right direction
actor Utilisateur
rectangle "Éditeur Graphique" {
  usecase "Importer une image" as UC_Import
  usecase "Depuis le device" as UC_Device
  usecase "Depuis un générateur IA" as UC_IA
}
Utilisateur --> UC_Import
UC_Import --> UC_Device
UC_Import --> UC_IA
@enduml